"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar1 from "./components/navbar/Navbar1";
import { useState, useEffect } from "react";
import Footer from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [lightMode, setlightMode] = useState();

  const useEffect =
    (() => {
      setlightMode(localStorage.getItem("darkMode") == true);
    },
    []);

  const toggleDarkMode = () => {
    setlightMode(!lightMode);
    localStorage.setItem("darkMode", lightMode);
  };
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${
          lightMode ? "light-background" : "dark-background"
        }`}
      >
        <Navbar1 toggleDarkMode={toggleDarkMode} darkMode={!lightMode} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
